"""apdate02

Revision ID: 63c277d3b439
Revises: db027321a588
Create Date: 2024-04-14 19:57:40.206962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c277d3b439'
down_revision: Union[str, None] = 'db027321a588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('grades', 'date_of')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_of', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###
